/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TutorRouteImport } from './routes/tutor'
import { Route as TopicosRouteImport } from './routes/topicos'
import { Route as PremiumRouteImport } from './routes/premium'
import { Route as ExameRouteImport } from './routes/exame'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TopicosSlugRouteImport } from './routes/topicos.$slug'
import { Route as QuizTopicSlugRouteImport } from './routes/quiz.$topicSlug'

const TutorRoute = TutorRouteImport.update({
  id: '/tutor',
  path: '/tutor',
  getParentRoute: () => rootRouteImport,
} as any)
const TopicosRoute = TopicosRouteImport.update({
  id: '/topicos',
  path: '/topicos',
  getParentRoute: () => rootRouteImport,
} as any)
const PremiumRoute = PremiumRouteImport.update({
  id: '/premium',
  path: '/premium',
  getParentRoute: () => rootRouteImport,
} as any)
const ExameRoute = ExameRouteImport.update({
  id: '/exame',
  path: '/exame',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TopicosSlugRoute = TopicosSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => TopicosRoute,
} as any)
const QuizTopicSlugRoute = QuizTopicSlugRouteImport.update({
  id: '/quiz/$topicSlug',
  path: '/quiz/$topicSlug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/exame': typeof ExameRoute
  '/premium': typeof PremiumRoute
  '/topicos': typeof TopicosRouteWithChildren
  '/tutor': typeof TutorRoute
  '/quiz/$topicSlug': typeof QuizTopicSlugRoute
  '/topicos/$slug': typeof TopicosSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/exame': typeof ExameRoute
  '/premium': typeof PremiumRoute
  '/topicos': typeof TopicosRouteWithChildren
  '/tutor': typeof TutorRoute
  '/quiz/$topicSlug': typeof QuizTopicSlugRoute
  '/topicos/$slug': typeof TopicosSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/exame': typeof ExameRoute
  '/premium': typeof PremiumRoute
  '/topicos': typeof TopicosRouteWithChildren
  '/tutor': typeof TutorRoute
  '/quiz/$topicSlug': typeof QuizTopicSlugRoute
  '/topicos/$slug': typeof TopicosSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/dashboard'
    | '/exame'
    | '/premium'
    | '/topicos'
    | '/tutor'
    | '/quiz/$topicSlug'
    | '/topicos/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth'
    | '/dashboard'
    | '/exame'
    | '/premium'
    | '/topicos'
    | '/tutor'
    | '/quiz/$topicSlug'
    | '/topicos/$slug'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/dashboard'
    | '/exame'
    | '/premium'
    | '/topicos'
    | '/tutor'
    | '/quiz/$topicSlug'
    | '/topicos/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  DashboardRoute: typeof DashboardRoute
  ExameRoute: typeof ExameRoute
  PremiumRoute: typeof PremiumRoute
  TopicosRoute: typeof TopicosRouteWithChildren
  TutorRoute: typeof TutorRoute
  QuizTopicSlugRoute: typeof QuizTopicSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tutor': {
      id: '/tutor'
      path: '/tutor'
      fullPath: '/tutor'
      preLoaderRoute: typeof TutorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/topicos': {
      id: '/topicos'
      path: '/topicos'
      fullPath: '/topicos'
      preLoaderRoute: typeof TopicosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/premium': {
      id: '/premium'
      path: '/premium'
      fullPath: '/premium'
      preLoaderRoute: typeof PremiumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exame': {
      id: '/exame'
      path: '/exame'
      fullPath: '/exame'
      preLoaderRoute: typeof ExameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/topicos/$slug': {
      id: '/topicos/$slug'
      path: '/$slug'
      fullPath: '/topicos/$slug'
      preLoaderRoute: typeof TopicosSlugRouteImport
      parentRoute: typeof TopicosRoute
    }
    '/quiz/$topicSlug': {
      id: '/quiz/$topicSlug'
      path: '/quiz/$topicSlug'
      fullPath: '/quiz/$topicSlug'
      preLoaderRoute: typeof QuizTopicSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface TopicosRouteChildren {
  TopicosSlugRoute: typeof TopicosSlugRoute
}

const TopicosRouteChildren: TopicosRouteChildren = {
  TopicosSlugRoute: TopicosSlugRoute,
}

const TopicosRouteWithChildren =
  TopicosRoute._addFileChildren(TopicosRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  DashboardRoute: DashboardRoute,
  ExameRoute: ExameRoute,
  PremiumRoute: PremiumRoute,
  TopicosRoute: TopicosRouteWithChildren,
  TutorRoute: TutorRoute,
  QuizTopicSlugRoute: QuizTopicSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
